#!/bin/sh

TMPFILE=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
OUTFILE=$(mktemp --tmpdir i3lock-wrapper-XXXXXXXXXX.png)
scrot $TMPFILE
convert $TMPFILE -scale 5% -scale 2000% $OUTFILE
i3lock -i $OUTFILE -d
rm $TMPFILE $OUTFILE
